/* generated by Svelte v3.55.1 */
"use strict";

const { create_ssr_component, escape } = require("svelte/internal");

const css = {
	code: ".cmp-button.svelte-r6b8v7{background-color:red;color:white}",
	map: "{\"version\":3,\"file\":null,\"sources\":[null],\"sourcesContent\":[\"<script>\\n    function handleClick() {\\n        console.log(\\\"you pressed me\\\");\\n    }\\n</script>\\n\\n<button\\n    on:click={handleClick}\\n    data-sly-use.button=\\\"com.adobe.cq.wcm.core.components.models.Button\\\"\\n    data-sly-use.iconTemplate=\\\"icon.html\\\"\\n    data-sly-element=\\\"${`{button.buttonLink.valid ? 'a' : 'button'}`}\\\"\\n    type=\\\"${`{button.buttonLink.valid ? '' : 'button'}`}\\\"\\n    id=\\\"${`{button.id}`}\\\"\\n    class=\\\"cmp-button\\\"\\n    data-sly-attribute=\\\"${`{button.buttonLink.htmlAttributes}`}\\\"\\n    aria-label=\\\"${`{button.accessibilityLabel}`}\\\"\\n    data-cmp-clickable=\\\"${`{button.data ? true : false}`}\\\"\\n    data-cmp-data-layer=\\\"${`{button.data.json}`}\\\"\\n>\\n    <sly data-sly-call=\\\"${`{iconTemplate.icon @ icon=button.icon}`}\\\" />\\n    <span data-sly-test=\\\"${`{button.text}`}\\\" class=\\\"cmp-button__text\\\">\\n        \\\"$button.text\\\"\\n    </span>\\n</button>\\n\\n<style>\\n    .cmp-button {\\n        background-color: red;\\n        color: white;\\n    }\\n</style>\\n\"],\"names\":[],\"mappings\":\"AA0BI,WAAW,cAAC,CAAC,AACT,gBAAgB,CAAE,GAAG,CACrB,KAAK,CAAE,KAAK,AAChB,CAAC\"}"
};

function handleClick() {
	console.log("you pressed me");
}

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<button data-sly-use.button="${"com.adobe.cq.wcm.core.components.models.Button"}" data-sly-use.icontemplate="${"icon.html"}" data-sly-element="${"$" + escape(`{button.buttonLink.valid ? 'a' : 'button'}`, true)}" type="${"$" + escape(`{button.buttonLink.valid ? '' : 'button'}`, true)}" id="${"$" + escape(`{button.id}`, true)}" class="${"cmp-button svelte-r6b8v7"}" data-sly-attribute="${"$" + escape(`{button.buttonLink.htmlAttributes}`, true)}" aria-label="${"$" + escape(`{button.accessibilityLabel}`, true)}" data-cmp-clickable="${"$" + escape(`{button.data ? true : false}`, true)}" data-cmp-data-layer="${"$" + escape(`{button.data.json}`, true)}"><sly data-sly-call="${"$" + escape(`{iconTemplate.icon @ icon=button.icon}`, true)}"></sly>
    <span data-sly-test="${"$" + escape(`{button.text}`, true)}" class="${"cmp-button__text"}">&quot;$button.text&quot;
    </span>
</button>`;
});

exports.default = Component;